# Generated by Django 5.1.3 on 2024-11-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('all_tickets', models.IntegerField()),
                ('tickets_left', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=40)),
            ],
        ),
    ]
