# Generated by Django 5.1.3 on 2024-11-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='all_tickets',
            new_name='available_tickets',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='tickets_left',
            new_name='total_tickets',
        ),
    ]
